apiVersion: v1
kind: Service
metadata:
  name: svc-auth-service
  labels:
    app: pod-auth-service
    env: dev
spec:
  selector:
    app: pod-auth-service
    env: dev
  type: NodePort
  ports:
  - name: http
    port: 8901
    targetPort: 8901
    nodePort: 32222
  - name: https
    port: 443
    targetPort: 8443
    nodePort: 32223

    
    
